# This is a basic workflow to help you get started with Actions

name: API CD

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ main ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    - name: Deploy using ssh
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.PRIVATE_KEY }}
        port: 22
        script: |
          cd ~/vps-simple-ci-cd-example
          git pull origin main
          git status
    - name: Create and populate .env file
      env:
        TEST_KEY: ${{ secrets.TEST_KEY }}
      run: |
        touch .env
        echo TEST_KEY=$TEST_KEY >> .env
    - name: Build API application
      run: |
        cd ~/vps-simple-ci-cd-example/api
        npm install
        npm run build
        pm2 restart api
